import { StyleSheet, Platform } from 'react-native';
import { COLORS, RADIUS, SHADOW, SPACING } from './theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F8F8',
  },
  centeredScreen: {
    justifyContent: 'center',
  },
  processingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
    backgroundColor: 'rgba(255,255,255,0.78)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  processingText: {
    marginTop: 10,
    fontWeight: '700',
    color: COLORS.black,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: SPACING.screenHeaderTop,
    paddingBottom: 15,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.black,
  },
  headerSpacer: {
    width: 24,
  },
  backButton: {
    padding: 4,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  section: {
    backgroundColor: COLORS.white,
    padding: 20,
    marginTop: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  inlineHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.black,
  },
  sectionTitleWithIcon: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.black,
    marginLeft: 8,
  },
  sectionMeta: {
    fontSize: 12,
    color: '#666',
  },
  productItem: {
    flexDirection: 'row',
    marginBottom: 15,
  },
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#F5F5F5',
  },
  productInfo: {
    flex: 1,
    marginLeft: 12,
  },
  productName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.black,
    lineHeight: 20,
  },
  productVariant: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  productPrice: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.black,
    marginTop: 6,
  },
  productQty: {
    fontSize: 12,
    color: COLORS.textSecondary,
    position: 'absolute',
    right: 0,
    bottom: 0,
  },
  addressContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  addressInfo: {
    flex: 1,
  },
  addressName: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 4,
  },
  addressText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  noAddressContainer: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  addAddressBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDD',
    borderStyle: 'dashed',
  },
  addAddressText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.black,
    marginLeft: 8,
  },
  changeAddressBtn: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  shippingCard: {
    marginTop: 15,
  },
  shippingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  shippingType: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.black,
  },
  shippingDesc: {
    fontSize: 13,
    color: '#666',
    marginLeft: 6,
  },
  shippingPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.success,
  },
  paymentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  paymentText: {
    fontSize: 14,
    color: COLORS.black,
    marginLeft: 10,
  },
  paymentValueWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  paymentValueText: {
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 6,
    marginRight: 6,
  },
  paymentMethodHint: {
    marginTop: 12,
    padding: 12,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  paymentMethodHintText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#475569',
  },
  divider: {
    height: 1,
    backgroundColor: '#F0F0F0',
    marginVertical: 15,
  },
  couponRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  couponSelectionText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
    marginRight: 6,
  },
  couponSelectionTextActive: {
    color: '#22C55E',
  },
  appliedCoupon: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: 12,
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  couponText: {
    fontSize: 13,
    color: COLORS.success,
    fontWeight: '600',
    marginHorizontal: 6,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  totalRow: {
    marginTop: 10,
  },
  summaryLabel: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  summaryValue: {
    fontSize: 14,
    color: COLORS.black,
    fontWeight: '500',
  },
  discountLabel: {
    color: '#EF4444',
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.black,
  },
  totalValue: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.success,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    padding: 20,
    paddingBottom: Platform.OS === 'ios' ? 35 : 20,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
    ...SHADOW.strong,
  },
  checkoutBtn: {
    backgroundColor: COLORS.accent,
    height: 54,
    borderRadius: RADIUS.lg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkoutBtnDisabled: {
    backgroundColor: '#E0E0E0',
  },
  checkoutBtnText: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.black,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '80%',
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.black,
  },
  modalList: {
    padding: 20,
  },
  addressOption: {
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEE',
    marginBottom: 12,
  },
  selectedAddressOption: {
    borderColor: COLORS.black,
    backgroundColor: '#F9F9F9',
  },
  couponOption: {
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEE',
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedCouponOption: {
    borderColor: '#22C55E',
    backgroundColor: '#F0FDF4',
  },
  couponOptionBody: {
    flex: 1,
    marginLeft: 12,
  },
  couponOptionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.black,
  },
  couponOptionSub: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  clearCouponOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEE',
    marginBottom: 12,
  },
  clearCouponText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 10,
    fontWeight: '600',
  },
  paymentMethodOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 12,
  },
  selectedPaymentMethodOption: {
    borderColor: COLORS.black,
    backgroundColor: '#FAFAFA',
  },
  paymentMethodIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentMethodBody: {
    flex: 1,
    marginLeft: 12,
    marginRight: 12,
  },
  paymentMethodTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.black,
  },
  paymentMethodSub: {
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
});
