import { StyleSheet, Platform, Dimensions } from 'react-native';
import { SPACING } from './theme';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F7F7',
  },
  loadingCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 100,
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: SPACING.screenHeaderTop,
    paddingBottom: 10,
    backgroundColor: '#F7F7F7',
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  iconButton: {
    padding: 2,
  },
  heroSection: {
    paddingHorizontal: 12,
    paddingTop: 10,
    alignItems: 'center',
  },
  mainImage: {
    width: '100%',
    height: 320,
    resizeMode: 'contain',
  },
  paginationDots: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  dot: {
    width: 20,
    height: 3,
    borderRadius: 999,
    backgroundColor: '#DFDFDF',
    marginHorizontal: 3,
  },
  activeDot: {
    backgroundColor: '#404040',
  },
  thumbContainer: {
    marginTop: 16,
  },
  thumbContent: {
    paddingHorizontal: 16,
    gap: 8,
  },
  thumbBox: {
    width: 80,
    height: 80,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DEDEDE',
    backgroundColor: '#FAFAFA',
    padding: 6,
  },
  activeThumb: {
    borderColor: '#1D1D1D',
    borderWidth: 1.5,
  },
  thumbImg: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  infoContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  productName: {
    fontSize: 22,
    lineHeight: 28,
    color: '#161616',
    fontWeight: '800',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  ratingValue: {
    marginLeft: 8,
    fontSize: 16,
    color: '#3C3C3C',
    fontWeight: '600',
  },
  reviewLink: {
    marginLeft: 6,
    fontSize: 14,
    color: '#8C8C8C',
    textDecorationLine: 'underline',
  },
  priceStatsRow: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    marginTop: 16,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  priceStatBox: {
    flex: 1,
    paddingHorizontal: 10,
  },
  verticalDivider: {
    borderLeftWidth: 1,
    borderLeftColor: '#ECECEC',
  },
  statLabel: {
    fontSize: 12,
    color: '#8C8C8C',
    marginBottom: 6,
  },
  statValue: {
    fontSize: 18,
    color: '#161616',
    fontWeight: '800',
  },
  guaranteeBanner: {
    marginTop: 16,
    backgroundColor: '#F0F0F0',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  guaranteeLogo: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#191919',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  guaranteeLogoText: {
    color: '#FFFFFF',
    fontSize: 9,
    lineHeight: 10,
    fontWeight: '800',
  },
  guaranteeText: {
    flex: 1,
    fontSize: 15,
    color: '#3A3A3A',
    fontWeight: '600',
  },
  sectionBlock: {
    backgroundColor: '#FFFFFF',
    marginTop: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  sectionAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  sectionTitle: {
    fontSize: 18,
    color: '#111111',
    fontWeight: '800',
  },
  sectionInner: {
    paddingBottom: 10,
  },
  reviewScoreCard: {
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 8,
    backgroundColor: '#F4F4F4',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewScoreValue: {
    fontSize: 36,
    color: '#161616',
    fontWeight: '800',
  },
  reviewScoreLabel: {
    marginTop: 1,
    fontSize: 15,
    color: '#666666',
  },
  reviewScoreRight: {
    alignItems: 'flex-end',
  },
  reviewStarsLarge: {
    flexDirection: 'row',
    gap: 2,
  },
  reviewCountText: {
    marginTop: 6,
    fontSize: 14,
    color: '#161616',
    fontWeight: '700',
  },
  fitSection: {
    marginTop: 24,
    marginBottom: 10,
  },
  fitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  fitLabel: {
    width: 100,
    fontSize: 14,
    color: '#4D4D4D',
  },
  fitBarTrack: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#E7E7E7',
    overflow: 'hidden',
    marginHorizontal: 12,
  },
  fitBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#151515',
  },
  fitPercent: {
    width: 36,
    textAlign: 'right',
    fontSize: 14,
    color: '#4D4D4D',
  },
  reviewCard: {
    marginTop: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#EAEAEA',
  },
  reviewContentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  reviewTextContent: {
    flex: 1,
    paddingRight: 12,
  },
  reviewSidePhoto: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#F5F5F5',
  },
  reviewTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  reviewDate: {
    marginLeft: 12,
    fontSize: 13,
    color: '#8C8C8C',
  },
  reviewUser: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111',
  },
  reviewComment: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: '#444',
  },
  moreReviewButton: {
    marginTop: 20,
    borderWidth: 1.5,
    borderColor: '#1F1F1F',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  moreReviewButtonText: {
    fontSize: 16,
    color: '#1A1A1A',
    fontWeight: '700',
  },
  detailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingTop: 10,
  },
  detailItem: {
    width: '50%',
    paddingBottom: 16,
    paddingRight: 16,
  },
  detailLabel: {
    fontSize: 13,
    color: '#7F7F7F',
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 16,
    color: '#1D1D1D',
    fontWeight: '600',
  },
  relatedSection: {
    marginTop: 20,
    paddingHorizontal: 16,
  },
  relatedTitle: {
    fontSize: 18,
    color: '#161616',
    fontWeight: '800',
    marginBottom: 12,
  },
  relatedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  bottomActionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E7E7E7',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  favoriteColumn: {
    width: 48,
    alignItems: 'center',
  },
  sellButton: {
    flex: 1,
    height: 56,
    borderRadius: 8,
    backgroundColor: '#161616',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buyButton: {
    flex: 1,
    height: 56,
    borderRadius: 8,
    backgroundColor: '#10D100',
    alignItems: 'center',
    justifyContent: 'center',
  },
  darkButtonText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  buyButtonText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  sizeModalContent: {
    height: '80%',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 10,
  },
  modalHandle: {
    width: 60,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#E0E0E0',
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalTabs: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#ECECEC',
  },
  modalTab: {
    flex: 1,
    alignItems: 'center',
    paddingBottom: 14,
  },
  modalTabActive: {
    borderBottomWidth: 2,
    borderBottomColor: '#111111',
  },
  modalTabText: {
    fontSize: 18,
    color: '#A9A9A9',
    fontWeight: '700',
  },
  modalTabTextActive: {
    color: '#161616',
    fontWeight: '800',
  },
  modalProductBrief: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  briefImg: {
    width: 60,
    height: 40,
    resizeMode: 'contain',
    marginRight: 12,
    backgroundColor: '#f9f9f9',
    borderRadius: 4,
  },
  briefInfo: {
    flex: 1,
  },
  briefName: {
    fontSize: 16,
    color: '#151515',
    fontWeight: '700',
  },
  briefMeta: {
    marginTop: 2,
    fontSize: 12,
    color: '#929292',
    fontWeight: '500',
  },
  sizeTabs: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  sizeTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 100,
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  sizeTabActive: {
    backgroundColor: '#111111',
    borderColor: '#111111',
  },
  sizeTabText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
  },
  sizeTabTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  sizeGridContent: {
    paddingHorizontal: 12,
    paddingBottom: 20,
  },
  sizeItem: {
    width: '31.3%',
    margin: '1%',
    minHeight: 100,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    backgroundColor: '#FFFFFF',
    padding: 12,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  activeSizeItem: {
    borderWidth: 2,
    borderColor: '#191919',
  },
  sizeText: {
    fontSize: 15,
    color: '#1B1B1B',
    fontWeight: '700',
  },
  sizePrice: {
    fontSize: 15,
    color: '#10D100',
    fontWeight: '700',
  },
  confirmBuyBtn: {
    marginHorizontal: 16,
    marginBottom: 30,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#10D100',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmBtnPrice: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '800',
  },
});
