import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS, SHADOW, SPACING } from './theme';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F6F2',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: SPACING.screenHeaderTop,
    paddingBottom: 12,
    backgroundColor: '#F6F6F2',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#ECECEC',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.black,
  },
  headerSpacer: {
    width: 40,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  metaBlock: {
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 18,
  },
  orderText: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 8,
  },
  amountText: {
    fontSize: 34,
    fontWeight: '900',
    color: '#0D0D0D',
    letterSpacing: -1,
    marginBottom: 8,
  },
  captionText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#6B7280',
    textAlign: 'center',
    maxWidth: 280,
  },
  qrContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    paddingTop: 18,
    paddingBottom: 24,
    paddingHorizontal: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ECECEC',
    ...SHADOW.strong,
    marginBottom: 18,
  },
  thaiQrImage: {
    width: 220,
    height: 40,
    resizeMode: 'contain',
    marginBottom: 4,
  },
  promptPayImage: {
    width: 112,
    height: 34,
    resizeMode: 'contain',
    marginBottom: 18,
  },
  qrWrapper: {
    width: Math.min(width - 68, 320),
    height: Math.min(width - 68, 320),
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  qrHint: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '600',
  },
  slipSection: {
    marginBottom: 4,
  },
  slipHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0D0D0D',
  },
  uploadedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#DCFCE7',
  },
  uploadedBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#166534',
    marginLeft: 4,
  },
  slipCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ECECEC',
  },
  slipPreview: {
    width: width - 80,
    maxWidth: 250,
    height: 300,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
  },
  emptySlipCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingVertical: 22,
    paddingHorizontal: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ECECEC',
    borderStyle: 'dashed',
  },
  emptySlipTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#111827',
    marginTop: 10,
    marginBottom: 4,
  },
  emptySlipText: {
    fontSize: 12,
    color: '#6B7280',
  },
  buttonContainer: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 30 : 16,
    backgroundColor: '#F6F6F2',
  },
  button: {
    height: 54,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    flexDirection: 'row',
    gap: 8,
  },
  saveButton: {
    backgroundColor: '#0D0D0D',
  },
  uploadButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DADADA',
  },
  confirmButton: {
    backgroundColor: COLORS.accent,
  },
  disabledButton: {
    backgroundColor: '#E5E7EB',
  },
  buttonText: {
    fontSize: 15,
    fontWeight: '800',
  },
  whiteText: {
    color: '#FFFFFF',
  },
  blackText: {
    color: '#0D0D0D',
  },
  grayText: {
    color: '#8B8B8B',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.22)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
    paddingHorizontal: 24,
  },
  loadingCard: {
    width: '100%',
    maxWidth: 280,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    ...SHADOW.card,
  },
  loadingText: {
    marginTop: 14,
    fontSize: 15,
    fontWeight: '700',
    color: '#0D0D0D',
    textAlign: 'center',
  },
});
