import { StyleSheet } from 'react-native';
import { SPACING } from './theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F7F7',
  },
  loadingCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 100,
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: SPACING.screenHeaderTop,
    paddingBottom: 10,
    backgroundColor: '#F7F7F7',
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  iconButton: {
    padding: 2,
  },
  installmentChip: {
    marginLeft: 16,
    marginTop: 4,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E6E6E6',
  },
  installmentChipText: {
    fontSize: 13,
    color: '#575757',
    fontWeight: '700',
  },
  heroSection: {
    paddingHorizontal: 12,
    paddingTop: 10,
    alignItems: 'center',
  },
  mainImage: {
    width: '100%',
    height: 320,
    resizeMode: 'contain',
  },
  paginationDots: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  dot: {
    width: 20,
    height: 3,
    borderRadius: 999,
    backgroundColor: '#DFDFDF',
    marginHorizontal: 3,
  },
  activeDot: {
    backgroundColor: '#404040',
  },
  thumbContainer: {
    marginTop: 16,
  },
  thumbContent: {
    paddingHorizontal: 16,
    gap: 8,
  },
  thumbBox: {
    width: 80,
    height: 80,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DEDEDE',
    backgroundColor: '#FAFAFA',
    padding: 6,
  },
  activeThumb: {
    borderColor: '#1D1D1D',
    borderWidth: 1.5,
  },
  thumbImg: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  infoContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  productName: {
    fontSize: 22,
    lineHeight: 28,
    color: '#161616',
    fontWeight: '800',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  ratingValue: {
    marginLeft: 8,
    fontSize: 16,
    color: '#3C3C3C',
    fontWeight: '600',
  },
  reviewLink: {
    marginLeft: 6,
    fontSize: 14,
    color: '#8C8C8C',
    textDecorationLine: 'underline',
  },
  priceStatsRow: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    marginTop: 16,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  priceStatBox: {
    flex: 1,
    paddingHorizontal: 10,
  },
  verticalDivider: {
    borderLeftWidth: 1,
    borderLeftColor: '#ECECEC',
  },
  statLabel: {
    fontSize: 12,
    color: '#8C8C8C',
    marginBottom: 6,
  },
  statValue: {
    fontSize: 18,
    color: '#161616',
    fontWeight: '800',
  },
  guaranteeBanner: {
    marginTop: 16,
    backgroundColor: '#F0F0F0',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  guaranteeLogo: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#191919',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  guaranteeLogoText: {
    color: '#FFFFFF',
    fontSize: 9,
    lineHeight: 10,
    fontWeight: '800',
  },
  guaranteeText: {
    flex: 1,
    fontSize: 15,
    color: '#3A3A3A',
    fontWeight: '600',
  },
  sectionBlock: {
    backgroundColor: '#FFFFFF',
    marginTop: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  sectionAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  sectionTitle: {
    fontSize: 18,
    color: '#111111',
    fontWeight: '800',
  },
  sectionInner: {
    paddingBottom: 10,
  },
  sectionTopSpacing: {
    paddingTop: 6,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  subSectionTitle: {
    fontSize: 16,
    color: '#151515',
    fontWeight: '800',
  },
  sectionSub: {
    marginTop: 4,
    fontSize: 13,
    color: '#7B7B7B',
  },
  viewMoreText: {
    fontSize: 14,
    color: '#646464',
    textDecorationLine: 'underline',
  },
  reviewPhotoRow: {
    paddingTop: 14,
    gap: 10,
  },
  reviewThumbnail: {
    width: 180,
    height: 160,
    borderRadius: 12,
    backgroundColor: '#F1F1F1',
  },
  reviewScoreCard: {
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 8,
    backgroundColor: '#F4F4F4',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewScoreValue: {
    fontSize: 36,
    color: '#161616',
    fontWeight: '800',
  },
  reviewScoreLabel: {
    marginTop: 1,
    fontSize: 15,
    color: '#666666',
  },
  reviewScoreRight: {
    alignItems: 'flex-end',
  },
  reviewStarsLarge: {
    flexDirection: 'row',
    gap: 2,
  },
  reviewCountText: {
    marginTop: 6,
    fontSize: 14,
    color: '#161616',
    fontWeight: '700',
  },
  fitSection: {
    marginTop: 24,
  },
  fitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  fitLabel: {
    width: 100,
    fontSize: 14,
    color: '#4D4D4D',
  },
  fitBarTrack: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#E7E7E7',
    overflow: 'hidden',
    marginHorizontal: 12,
  },
  fitBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#151515',
  },
  fitPercent: {
    width: 36,
    textAlign: 'right',
    fontSize: 14,
    color: '#4D4D4D',
  },
  reviewCard: {
    marginTop: 24,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#EAEAEA',
  },
  reviewTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewDate: {
    marginLeft: 12,
    fontSize: 13,
    color: '#8C8C8C',
  },
  reviewMeta: {
    marginTop: 8,
    fontSize: 14,
    color: '#5D5D5D',
  },
  fitBadge: {
    marginTop: 14,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#F3F3F3',
  },
  fitBadgeText: {
    fontSize: 13,
    color: '#353535',
    fontWeight: '700',
  },
  reviewComment: {
    marginTop: 14,
    fontSize: 15,
    lineHeight: 22,
    color: '#202020',
  },
  moreReviewButton: {
    marginTop: 20,
    borderWidth: 1.5,
    borderColor: '#1F1F1F',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  moreReviewButtonText: {
    fontSize: 16,
    color: '#1A1A1A',
    fontWeight: '600',
  },
  detailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingTop: 10,
  },
  detailItem: {
    width: '50%',
    paddingBottom: 16,
    paddingRight: 16,
  },
  detailLabel: {
    fontSize: 13,
    color: '#7F7F7F',
    marginBottom: 4,
  },
  detailLink: {
    fontSize: 16,
    color: '#1D1D1D',
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  detailValue: {
    fontSize: 16,
    color: '#1D1D1D',
    lineHeight: 22,
  },
  linkSection: {
    backgroundColor: '#FFFFFF',
    marginTop: 10,
    paddingHorizontal: 16,
  },
  linkRow: {
    minHeight: 60,
    borderTopWidth: 1,
    borderTopColor: '#ECECEC',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  linkRowText: {
    fontSize: 16,
    color: '#141414',
    fontWeight: '700',
  },
  linkPanel: {
    paddingBottom: 14,
  },
  linkPanelText: {
    fontSize: 14,
    color: '#5F5F5F',
    lineHeight: 20,
  },
  saleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  saleSize: {
    fontSize: 14,
    color: '#191919',
  },
  salePrice: {
    fontSize: 16,
    color: '#191919',
    fontWeight: '800',
  },
  promoCard: {
    marginTop: 16,
    marginHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#EEF2D8',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  promoIconBox: {
    width: 50,
    height: 34,
    borderRadius: 6,
    backgroundColor: '#1C1C1C',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    transform: [{ rotate: '-12deg' }],
  },
  promoIconText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
  },
  promoContent: {
    flex: 1,
  },
  promoTitle: {
    fontSize: 16,
    color: '#1A1A1A',
    fontWeight: '800',
    marginBottom: 2,
  },
  promoText: {
    fontSize: 13,
    color: '#4E5543',
    lineHeight: 18,
  },
  relatedSection: {
    marginTop: 20,
    paddingHorizontal: 16,
  },
  relatedTitle: {
    fontSize: 18,
    color: '#161616',
    fontWeight: '800',
    marginBottom: 12,
  },
  relatedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  relatedCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  relatedImage: {
    width: '100%',
    height: 120,
    resizeMode: 'contain',
  },
  relatedBrand: {
    marginTop: 10,
    fontSize: 15,
    color: '#171717',
    fontWeight: '800',
  },
  relatedName: {
    marginTop: 2,
    fontSize: 14,
    lineHeight: 18,
    color: '#3F3F3F',
    minHeight: 36,
  },
  relatedPriceLabel: {
    marginTop: 16,
    fontSize: 12,
    color: '#7B7B7B',
  },
  relatedPriceRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  relatedPrice: {
    fontSize: 18,
    color: '#151515',
    fontWeight: '800',
  },
  bottomActionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E7E7E7',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  favoriteColumn: {
    width: 48,
    alignItems: 'center',
  },
  favoriteCount: {
    marginTop: 4,
    fontSize: 14,
    color: '#232323',
  },
  sellButton: {
    flex: 1,
    height: 56,
    borderRadius: 8,
    backgroundColor: '#161616',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buyButton: {
    flex: 1,
    height: 56,
    borderRadius: 8,
    backgroundColor: '#10D100',
    alignItems: 'center',
    justifyContent: 'center',
  },
  darkButtonText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  buyButtonText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  sizeModalContent: {
    height: '70%',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 10,
  },
  modalHandle: {
    width: 60,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#E0E0E0',
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalTabs: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#ECECEC',
  },
  modalTab: {
    flex: 1,
    alignItems: 'center',
    paddingBottom: 14,
  },
  modalTabActive: {
    borderBottomWidth: 2,
    borderBottomColor: '#111111',
  },
  modalTabText: {
    fontSize: 16,
    color: '#A9A9A9',
  },
  modalTabTextActive: {
    color: '#161616',
    fontWeight: '800',
  },
  modalProductBrief: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  briefImg: {
    width: 70,
    height: 50,
    resizeMode: 'contain',
    marginRight: 12,
  },
  briefInfo: {
    flex: 1,
  },
  briefName: {
    fontSize: 16,
    color: '#151515',
    fontWeight: '700',
  },
  briefMeta: {
    marginTop: 2,
    fontSize: 13,
    color: '#929292',
  },
  sizeTabs: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 6,
    gap: 8,
  },
  sizeTab: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#DEDEDE',
    backgroundColor: '#FFFFFF',
  },
  sizeTabActive: {
    backgroundColor: '#111111',
    borderColor: '#111111',
  },
  sizeTabText: {
    fontSize: 14,
    color: '#3C3C3C',
  },
  sizeTabTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  sizeGridContent: {
    paddingHorizontal: 10,
    paddingBottom: 16,
  },
  sizeItem: {
    width: '31.3%',
    margin: '1%',
    minHeight: 90,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E2E2',
    backgroundColor: '#FFFFFF',
    paddingTop: 12,
    paddingHorizontal: 8,
  },
  activeSizeItem: {
    borderWidth: 2,
    borderColor: '#191919',
  },
  disabledSizeItem: {
    backgroundColor: '#FAFAFA',
  },
  sizeItemTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  sizeText: {
    fontSize: 15,
    color: '#1B1B1B',
    fontWeight: '600',
  },
  disabledSizeText: {
    color: '#B7B7B7',
  },
  sizePrice: {
    marginTop: 10,
    fontSize: 15,
    color: '#20B84C',
    fontWeight: '700',
  },
  disabledSizePrice: {
    color: '#BFBFBF',
  },
  confirmBuyBtn: {
    marginHorizontal: 16,
    marginBottom: 16,
    height: 70,
    borderRadius: 10,
    backgroundColor: '#10D100',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  confirmBtnLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  flashBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  confirmBtnMainText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  confirmBtnRight: {
    alignItems: 'flex-end',
  },
  confirmBtnPrice: {
    fontSize: 20,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  confirmBtnSub: {
    marginTop: 2,
    fontSize: 13,
    color: '#EDFFED',
  },
  reviewUser: {
    fontWeight: "600",
    fontSize: 14,
    marginTop: 4
  },
});
